from rdkit import RDConfig as RDConfig
from rdkit.Chem.Draw.canvasbase import CanvasBase as CanvasBase
from typing import Any

faceMap: Any

def convertColor(color): ...

class Canvas(CanvasBase):
    fontScale: float
    image: Any
    draw: Any
    size: Any
    drawType: Any
    fileName: Any
    def __init__(self, img: Any | None = ..., imageType: Any | None = ..., fileName: Any | None = ..., size: Any | None = ...) -> None: ...
    def addCanvasLine(self, p1, p2, color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def addCanvasText(self, text, pos, font, color=..., **kwargs): ...
    def addCanvasPolygon(self, ps, color=..., fill: bool = ..., stroke: bool = ..., **kwargs) -> None: ...
    def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def flush(self) -> None: ...
