from rdkit.Chem.Draw.canvasbase import CanvasBase as CanvasBase
from typing import Any

class Canvas(CanvasBase):
    size: Any
    qsize: Any
    pixmap: Any
    painter: Any
    def __init__(self, size) -> None: ...
    def addCanvasLine(self, p1, p2, color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def addCanvasText(self, text, pos, font, color=..., **kwargs): ...
    def addCanvasPolygon(self, ps, color=..., fill: bool = ..., stroke: bool = ..., **kwargs) -> None: ...
    def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def flush(self) -> None: ...
