from rdkit.Chem.Draw.canvasbase import CanvasBase as CanvasBase
from rdkit.sping import pid as pid
from typing import Any

faceMap: Any

def convertColor(color): ...

class Canvas(CanvasBase):
    canvas: Any
    size: Any
    def __init__(self, size, name, imageType: str = ...) -> None: ...
    def addCanvasLine(self, p1, p2, color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def addCanvasText(self, text, pos, font, color=..., **kwargs): ...
    def addCanvasPolygon(self, ps, color=..., fill: bool = ..., stroke: bool = ..., **kwargs) -> None: ...
    def addCanvasDashedWedge(self, p1, p2, p3, dash=..., color=..., color2: Any | None = ..., **kwargs) -> None: ...
    def flush(self) -> None: ...
    def save(self) -> None: ...
