from typing import Any

StandardEnglishFonts: Any
widths: Any
ascent_descent: Any

def parseAFMfile(filename): ...

class FontCache:
    def __init__(self) -> None: ...
    def loadfont(self, fontname) -> None: ...
    def getfont(self, fontname): ...
    def stringwidth(self, text, font): ...
    def status(self): ...

TheFontCache: Any
stringwidth: Any
