from rdkit import Chem as Chem
from rdkit.Chem import rdMolDescriptors as rdMolDescriptors
from typing import Any

def ExplainAtomCode(code, branchSubtract: int = ..., includeChirality: bool = ...): ...

GetAtomCode: Any

def NumPiElectrons(atom): ...
def BitsInCommon(v1, v2): ...
def DiceSimilarity(v1, v2, bounds: Any | None = ...): ...
def Dot(v1, v2): ...
def CosineSimilarity(v1, v2): ...
