from rdkit.VLib.Node import VLibNode as VLibNode
from typing import Any

class FilterNode(VLibNode):
    def __init__(self, func: Any | None = ..., negate: int = ..., **kwargs) -> None: ...
    def SetNegate(self, state) -> None: ...
    def Negate(self): ...
    def next(self): ...
