from rdkit.VLib.Node import VLibNode as VLibNode
from typing import Any

class SupplyNode(VLibNode):
    def __init__(self, contents: Any | None = ..., **kwargs) -> None: ...
    def reset(self) -> None: ...
    def next(self): ...
    def AddParent(self, parent, notify: int = ...) -> None: ...
