from rdkit import Geometry as Geometry
from rdkit.Chem.FeatMaps import FeatMapPoint as FeatMapPoint, FeatMaps as FeatMaps
from typing import Any

class FeatMapParseError(ValueError): ...

class FeatMapParser:
    data: Any
    def __init__(self, file: Any | None = ..., data: Any | None = ...) -> None: ...
    def SetData(self, data) -> None: ...
    def Parse(self, featMap: Any | None = ...): ...
    def ParseParamBlock(self): ...
    def ParseFeatPointBlock(self): ...
