from rdkit.Chem import ChemicalFeatures as ChemicalFeatures
from typing import Any

class FeatMapPoint(ChemicalFeatures.FreeChemicalFeature):
    weight: float
    featDirs: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def initFromFeat(self, feat) -> None: ...
    def GetDist2(self, other): ...
    def GetDirMatch(self, other, useBest: bool = ...): ...
