from rdkit import RDConfig as RDConfig
from typing import Any

TEST_FAILED: int
TEST_PASSED: int
BUILD_TYPE_ENVVAR: str

def isDebugBuild(): ...
def RunTest(exeName, args, extras): ...
def RunScript(script, doLongTests, verbose): ...
def ReportResults(script, failedTests, nTests, runTime, verbose, dest) -> None: ...

class _RedirectStream:
    def __init__(self, new_target) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exctype, excinst, exctb) -> None: ...

class redirect_stdout(_RedirectStream): ...
class redirect_stderr(_RedirectStream): ...

class OutputRedirectC:
    outfiles: Any
    combine: Any
    mode: Any
    saved_streams: Any
    fds: Any
    saved_fds: Any
    null_fds: Any
    null_streams: Any
    def __init__(self, stdout=..., stderr=..., mode: str = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args): ...
