from rdkit import DataStructs as DataStructs
from rdkit.VLib.Node import VLibNode as VLibNode
from typing import Any

class DbFpSupplier(VLibNode):
    fpCol: Any
    def __init__(self, dbResults, fpColName: str = ..., usePickles: bool = ...) -> None: ...
    def GetColumnNames(self): ...
    def next(self): ...
    __next__: Any

class ForwardDbFpSupplier(DbFpSupplier):
    def __init__(self, *args, **kwargs) -> None: ...
    def reset(self) -> None: ...
    def NextItem(self): ...

class RandomAccessDbFpSupplier(DbFpSupplier):
    def __init__(self, *args, **kwargs) -> None: ...
    def __len__(self): ...
    def __getitem__(self, idx): ...
    def reset(self) -> None: ...
    def NextItem(self): ...
