from rdkit import DataStructs as DataStructs
from rdkit.DataStructs import TopNContainer as TopNContainer
from typing import Any

class SimilarityScreener:
    metric: Any
    dataSource: Any
    fingerprinter: Any
    probe: Any
    def __init__(self, probe: Any | None = ..., metric: Any | None = ..., dataSource: Any | None = ..., fingerprinter: Any | None = ...) -> None: ...
    def Reset(self) -> None: ...
    def SetProbe(self, probeFingerprint) -> None: ...
    def GetSingleFingerprint(self, probe): ...

class ThresholdScreener(SimilarityScreener):
    threshold: Any
    dataIter: Any
    def __init__(self, threshold, **kwargs) -> None: ...
    def Reset(self) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    __next__: Any

class TopNScreener(SimilarityScreener):
    numToGet: Any
    topN: Any
    def __init__(self, num, **kwargs) -> None: ...
    def Reset(self) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    __next__: Any
    def __len__(self): ...
    def __getitem__(self, idx): ...
