from rdkit.DataStructs.TopNContainer import TopNContainer as TopNContainer
from typing import Any

class KNNModel:
    def __init__(self, k, attrs, dfunc, radius: Any | None = ...) -> None: ...
    def GetName(self): ...
    def SetName(self, name) -> None: ...
    def GetExamples(self): ...
    def SetExamples(self, examples) -> None: ...
    def GetTrainingExamples(self): ...
    def SetTrainingExamples(self, examples) -> None: ...
    def GetTestExamples(self): ...
    def SetTestExamples(self, examples) -> None: ...
    def GetNeighbors(self, example): ...
