from typing import Any

class ActFunc:
    def __call__(self, x): ...

class Sigmoid(ActFunc):
    def Eval(self, x): ...
    def Deriv(self, x): ...
    def DerivFromVal(self, val): ...
    beta: Any
    def __init__(self, beta: float = ...) -> None: ...

class TanH(ActFunc):
    def Eval(self, x): ...
    def Deriv(self, x): ...
    def DerivFromVal(self, val): ...
    beta: Any
    def __init__(self, beta: float = ...) -> None: ...
