from . import ActFuncs as ActFuncs
from typing import Any

class NetNode:
    def Eval(self, valVect): ...
    inputNodes: Any
    def SetInputs(self, inputNodes) -> None: ...
    def GetInputs(self): ...
    weights: Any
    def SetWeights(self, weights) -> None: ...
    def GetWeights(self): ...
    nodeIndex: Any
    nodeList: Any
    actFunc: Any
    def __init__(self, nodeIndex, nodeList, inputNodes: Any | None = ..., weights: Any | None = ..., actFunc=..., actFuncParms=...) -> None: ...
