from rdkit.Chem.Pharm2D import Utils as Utils
from rdkit.Chem.Pharmacophores import cUtils as cUtils
from rdkit.DataStructs import IntSparseIntVect as IntSparseIntVect, LongSparseIntVect as LongSparseIntVect, SparseBitVect as SparseBitVect
from typing import Any

class SigFactory:
    featFactory: Any
    useCounts: Any
    minPointCount: Any
    maxPointCount: Any
    shortestPathsOnly: Any
    includeBondOrder: Any
    trianglePruneBins: Any
    skipFeats: Any
    sigKlass: Any
    def __init__(self, featFactory, useCounts: bool = ..., minPointCount: int = ..., maxPointCount: int = ..., shortestPathsOnly: bool = ..., includeBondOrder: bool = ..., skipFeats: Any | None = ..., trianglePruneBins: bool = ...) -> None: ...
    def SetBins(self, bins) -> None: ...
    def GetBins(self): ...
    def GetNumBins(self): ...
    def GetSignature(self): ...
    def GetBitDescriptionAsText(self, bitIdx, includeBins: int = ..., fullPage: int = ...) -> None: ...
    def GetBitDescription(self, bitIdx): ...
    def GetFeatFamilies(self): ...
    def GetMolFeats(self, mol): ...
    def GetBitIdx(self, featIndices, dists, sortIndices: bool = ...): ...
    def GetBitInfo(self, idx): ...
    def Init(self) -> None: ...
    def GetSigSize(self): ...
