from rdkit.sping.pid import *
from typing import Any

f: Any

class PILCanvas(Canvas):
    def __init__(self, size=..., name: str = ...) -> None: ...
    def __setattr__(self, attribute, value) -> None: ...
    def getImage(self): ...
    def save(self, file: Any | None = ..., format: Any | None = ...) -> None: ...
    def clear(self) -> None: ...
    def stringWidth(self, s, font: Any | None = ...): ...
    def fontAscent(self, font: Any | None = ...): ...
    def fontDescent(self, font: Any | None = ...): ...
    def drawLine(self, x1, y1, x2, y2, color: Any | None = ..., width: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawPolygon(self, pointlist, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., closed: int = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawString(self, s, x, y, font: Any | None = ..., color: Any | None = ..., angle: int = ..., **kwargs): ...
    def drawImage(self, image, x1, y1, x2: Any | None = ..., y2: Any | None = ..., **kwargs) -> None: ...

def test(): ...
def testit(canvas, s, x, y, font: Any | None = ...) -> None: ...
def test2() -> None: ...
