from typing import Any

def EuclideanDistance(inData): ...
def CalcMetricMatrix(inData, metricFunc): ...
def FindMinValInList(mat, nObjs, minIdx: Any | None = ...): ...
def ShowMetricMat(metricMat, nObjs) -> None: ...

methods: Any
