from openmm.unit import Unit

meter_base_unit: Unit
meters: Unit
meter: Unit
angstrom_base_unit: Unit
angstroms: Unit
angstrom: Unit
planck_length_base_unit: Unit
inch_base_unit: Unit
inch: Unit
inches: Unit
foot_base_unit: Unit
foot: Unit
feet: Unit
yard_base_unit: Unit
yard: Unit
yards: Unit
furlongs: Unit
furlong: Unit
miles: Unit
mile: Unit
bohrs: Unit
bohr: Unit
gram_base_unit: Unit
grams: Unit
gram: Unit
planck_mass_base_unit: Unit
pound_mass_base_unit: Unit
pound_mass: Unit
pounds_mass: Unit
stone_base_unit: Unit
stone: Unit
stones: Unit
second_base_unit: Unit
seconds: Unit
second: Unit
planck_time_base_unit: Unit
minutes: Unit
minute: Unit
hours: Unit
hour: Unit
days: Unit
day: Unit
weeks: Unit
week: Unit
years: Unit
year: Unit
centuries: Unit
centurys: Unit
century: Unit
millenia: Unit
milleniums: Unit
millenium: Unit
fortnights: Unit
fortnight: Unit
kelvin_base_unit: Unit
kelvins: Unit
kelvin: Unit
planck_temperature_base_unit: Unit
elementary_charge_base_unit: Unit
elementary_charges: Unit
elementary_charge: Unit
coulomb_base_unit: Unit
coulombs: Unit
coulomb: Unit
planck_charge_base_unit: Unit
mole_base_unit: Unit
moles: Unit
mole: Unit
single_item_amount_base_unit: Unit
items: Unit
item: Unit
candela_base_unit: Unit
candelas: Unit
candela: Unit
radian_base_unit: Unit
radians: Unit
radian: Unit
degree_base_unit: Unit
degrees: Unit
degree: Unit
arcminutes: Unit
arcminute: Unit
arcseconds: Unit
arcsecond: Unit
bit_base_unit: Unit
bits: Unit
bit: Unit
byte_base_unit: Unit
bytes: Unit
byte: Unit
nat_base_unit: Unit
nats: Unit
nat: Unit
nits: Unit
nit: Unit
nepits: Unit
nepit: Unit
ban_base_unit: Unit
bans: Unit
ban: Unit
hartleys: Unit
hartley: Unit
dits: Unit
dit: Unit
daltons: Unit
dalton: Unit
amus = dalton
amu = dalton
atom_mass_units = dalton
atomic_mass_unit = dalton
liter_base_unit: Unit
liter: Unit
liters: Unit
litre: Unit
litres: Unit
molar_base_unit: Unit
molar: Unit
molal: Unit
newton_base_unit: Unit
newtons: Unit
newton: Unit
pound_force_base_unit: Unit
pound_force: Unit
pounds_force: Unit
dyne_base_unit: Unit
dyne: Unit
dynes: Unit
joule_base_unit: Unit
joules: Unit
joule: Unit
erg_base_unit: Unit
erg: Unit
ergs: Unit
hartree_base_unit: Unit
hartree: Unit
hartrees: Unit
md_kilojoule_raw: Unit
md_kilojoules: Unit
md_kilojoule: Unit
kilojoules_per_mole: Unit
kilojoule_per_mole: Unit
calorie_base_unit: Unit
calories: Unit
calorie: Unit
md_kilocalories: Unit
md_kilocalorie: Unit
kilocalories_per_mole: Unit
kilocalorie_per_mole: Unit
watt_base_unit: Unit
watt: Unit
watts: Unit
ampere_base_unit: Unit
ampere: Unit
amperes: Unit
amp: Unit
amps: Unit
volt_base_unit: Unit
volt: Unit
volts: Unit
tesla_base_unit: Unit
tesla: Unit
teslas: Unit
gauss_base_unit: Unit
gauss: Unit
ohm_base_unit: Unit
ohm: Unit
ohms: Unit
farad_base_unit: Unit
farad: Unit
farads: Unit
henry_base_unit: Unit
henry: Unit
henries: Unit
henrys: Unit
debye_base_unit: Unit
debyes: Unit
debye: Unit
pascal_base_unit: Unit
pascals: Unit
pascal: Unit
psi_base_unit: Unit
psi: Unit
bar_base_unit: Unit
bar: Unit
bars: Unit
atmosphere_base_unit: Unit
atmosphere: Unit
atmospheres: Unit
torr_base_unit: Unit
torr: Unit
mmHg_base_unit: Unit
mmHg: Unit
si_unit_system: Unit
cgs_unit_system: Unit
dalton_base_unit: Unit
md_unit_system: Unit
planck_unit_system: Unit


# Shim for common units, otherwise created at runtime
nanometer: Unit
nanometers: Unit
femtosecond: Unit
femtoseconds: Unit
