from .unit_definitions import *
from .quantity import is_quantity as is_quantity

def sin(angle): ...
def sinh(angle): ...
def cos(angle): ...
def cosh(angle): ...
def tan(angle): ...
def tanh(angle): ...
def acos(x): ...
def acosh(x): ...
def asin(x): ...
def asinh(x): ...
def atan(x): ...
def atanh(x): ...
def atan2(x, y): ...
def sqrt(val): ...
def sum(val): ...
def dot(x, y): ...
def norm(x): ...
