from rdkit import RDConfig as RDConfig
from rdkit.Dbase import DbModule as DbModule
from typing import Any

sqlTextTypes: Any
sqlIntTypes: Any
sqlFloatTypes: Any
sqlBinTypes: Any

def GetDbNames(user: str = ..., password: str = ..., dirName: str = ..., dBase: str = ..., cn: Any | None = ...): ...
def GetTableNames(dBase, user: str = ..., password: str = ..., includeViews: int = ..., cn: Any | None = ...): ...
def GetColumnInfoFromCursor(cursor): ...
def GetColumnNamesAndTypes(dBase, table, user: str = ..., password: str = ..., join: str = ..., what: str = ..., cn: Any | None = ...): ...
def GetColumnNames(dBase, table, user: str = ..., password: str = ..., join: str = ..., what: str = ..., cn: Any | None = ...): ...
