from rdkit.Dbase import DbInfo as DbInfo
from typing import Any

class DbResultBase:
    cursor: Any
    removeDups: Any
    transform: Any
    cmd: Any
    conn: Any
    extras: Any
    def __init__(self, cursor, conn, cmd, removeDups: int = ..., transform: Any | None = ..., extras: Any | None = ...) -> None: ...
    def Reset(self) -> None: ...
    def __iter__(self): ...
    def GetColumnNames(self): ...
    def GetColumnTypes(self): ...
    def GetColumnNamesAndTypes(self): ...

class DbResultSet(DbResultBase):
    seen: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def Reset(self) -> None: ...
    def next(self): ...
    __next__: Any

class RandomAccessDbResultSet(DbResultBase):
    results: Any
    seen: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def Reset(self) -> None: ...
    cursor: Any
    def __getitem__(self, idx): ...
    def __len__(self): ...
    def next(self): ...
    __next__: Any
