from typing import Any

class DescriptorCalculator:
    simpleList: Any
    descriptorNames: Any
    compoundList: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def ShowDescriptors(self) -> None: ...
    def GetDescriptorNames(self) -> None: ...
    def SaveState(self, fileName) -> None: ...
    def CalcDescriptors(self, what, *args, **kwargs) -> None: ...
