from rdkit.ML.Descriptors import Descriptors as Descriptors
from rdkit.RDLogger import logger as logger
from typing import Any

class MolecularDescriptorCalculator(Descriptors.DescriptorCalculator):
    simpleList: Any
    descriptorNames: Any
    compoundList: Any
    def __init__(self, simpleList, *args, **kwargs) -> None: ...
    def SaveState(self, fileName) -> None: ...
    def CalcDescriptors(self, mol, *args, **kwargs): ...
    def GetDescriptorNames(self): ...
    def GetDescriptorSummaries(self): ...
    def GetDescriptorFuncs(self): ...
    def GetDescriptorVersions(self): ...
