from wxPython.wx import *
from rdkit.sping import pid as sping_pid
from typing import Any

class WxCanvasError(RuntimeError): ...

class PiddleWxDc(sping_pid.Canvas):
    dc: Any
    def __init__(self, aWxDc, size=..., name: str = ...) -> None: ...
    def __del__(self) -> None: ...
    def isInteractive(self): ...
    def canUpdate(self): ...
    def clear(self) -> None: ...
    def stringWidth(self, s, font: Any | None = ...): ...
    def fontHeight(self, font: Any | None = ...): ...
    def fontAscent(self, font: Any | None = ...): ...
    def fontDescent(self, font: Any | None = ...): ...
    def drawLine(self, x1, y1, x2, y2, color: Any | None = ..., width: Any | None = ...) -> None: ...
    def drawString(self, s, x, y, font: Any | None = ..., color: Any | None = ..., angle: Any | None = ...) -> None: ...
    def drawPolygon(self, pointlist, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., closed: int = ...): ...
    def drawImage(self, image, x1, y1, x2: Any | None = ..., y2: Any | None = ...) -> None: ...
