from wxPython.wx import *
from pidWxDc import PiddleWxDc
from typing import Any

__date__: str

class _WXCanvasDefaultStatusBar(wxStatusBar):
    parentwindow: Any
    sizeChanged: Any
    text: str
    old_text: str
    canvas: Any
    quitButton: Any
    clearButton: Any
    click: Any
    def __init__(self, canvas, pos, size) -> None: ...
    def repaint(self, event) -> None: ...
    def redraw(self) -> None: ...
    def draw(self, dc) -> None: ...
    def SetStatusText(self, s) -> None: ...
    def OnOver(self, x, y) -> None: ...
    def OnClick(self, x, y) -> None: ...
    def OnLeaveWindow(self) -> None: ...
    def OnClickUp(self, x, y) -> None: ...
    def OnSize(self, evt) -> None: ...
    def OnIdle(self, evt) -> None: ...
    def Reposition(self) -> None: ...

class WXCanvas(PiddleWxDc):
    window: Any
    MemDc: Any
    size: Any
    sb: Any
    onClick: Any
    onOver: Any
    onKey: Any
    onClickUp: Any
    interactive: Any
    onLeaveWindow: Any
    def __init__(self, size=..., name: str = ..., status_bar: Any | None = ..., interactive: int = ..., show_status: int = ...) -> None: ...
    def isInteractive(self): ...
    def canUpdate(self): ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def setInfoLine(self, s) -> None: ...
