from rdkit import Chem as Chem
from rdkit.Chem.Suppliers.MolSupplier import MolSupplier as MolSupplier
from typing import Any

def warning(msg, dest=...) -> None: ...

class DbMolSupplier(MolSupplier):
    molCol: int
    transformFunc: Any
    nameCol: Any
    molFmt: Any
    def __init__(self, dbResults, molColumnFormats=..., nameCol: str = ..., transformFunc: Any | None = ..., **kwargs) -> None: ...
    def GetColumnNames(self): ...

class ForwardDbMolSupplier(DbMolSupplier):
    def __init__(self, dbResults, **kwargs) -> None: ...
    def Reset(self) -> None: ...
    def NextMol(self): ...

class RandomAccessDbMolSupplier(DbMolSupplier):
    def __init__(self, dbResults, **kwargs) -> None: ...
    def __len__(self): ...
    def __getitem__(self, idx): ...
    def Reset(self) -> None: ...
    def NextMol(self): ...
