from rdkit import RDConfig as RDConfig
from typing import Any

def SmilesToGif(smiles, fileNames, size=..., cmd: Any | None = ..., dblSize: int = ..., frame: int = ...): ...
def SmilesToImage(smiles, **kwargs): ...
