from rdkit.sping.pid import *
from math import *
from rdkit.sping.PDF import pdfmetrics as pdfmetrics, pidPDF as pidPDF
from typing import Any

def colorToRL(color): ...

class RLCanvas(Canvas):
    size: Any
    drawing: Any
    def __init__(self, size=..., name: str = ...) -> None: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def save(self, file: Any | None = ..., format: Any | None = ...) -> None: ...
    def fixY(self, y): ...
    def drawLine(self, x1, y1, x2, y2, color: Any | None = ..., width: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawCurve(self, x1, y1, x2, y2, x3, y3, x4, y4, closed: int = ..., **kwargs) -> None: ...
    def drawArc(self, x1, y1, x2, y2, startAng: int = ..., extent: int = ..., edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawPolygon(self, pointlist, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor=..., closed: int = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawString(self, s, x, y, font: Any | None = ..., color: Any | None = ..., angle: int = ..., **kwargs) -> None: ...
    def drawImage(self, image, x1, y1, x2: Any | None = ..., y2: Any | None = ..., **kwargs) -> None: ...
    def stringWidth(self, s, font: Any | None = ...): ...
    def fontAscent(self, font: Any | None = ...): ...
    def fontDescent(self, font: Any | None = ...): ...

def test(): ...
def dashtest(): ...
def testit(canvas, s, x, y, font: Any | None = ...) -> None: ...
def test2() -> None: ...
