from typing import Any

class BitEnsemble:
    def __init__(self, bits: Any | None = ...) -> None: ...
    def SetBits(self, bits) -> None: ...
    def AddBit(self, bit) -> None: ...
    def GetBits(self): ...
    def GetNumBits(self): ...
    def ScoreWithOnBits(self, other): ...
    def ScoreWithIndex(self, other): ...
