from typing import Any

class TopNContainer:
    best: Any
    extras: Any
    def __init__(self, size, mostNeg=...) -> None: ...
    def Insert(self, val, extra: Any | None = ...) -> None: ...
    def GetPts(self): ...
    def GetExtras(self): ...
    def __len__(self): ...
    def __getitem__(self, which): ...
    def reverse(self) -> None: ...
