from rdkit import DataStructs as DataStructs
from typing import Any

class VectCollection:
    def __init__(self) -> None: ...
    def GetOrVect(self): ...
    orVect: Any
    def AddVect(self, idx, vect) -> None: ...
    def Reset(self) -> None: ...
    def NumChildren(self): ...
    def GetChildren(self): ...
    def __getitem__(self, idx): ...
    GetBit: Any
    def __len__(self): ...
    GetNumBits: Any
    def GetOnBits(self): ...
    def DetachVectsNotMatchingBit(self, bit) -> None: ...
    def DetachVectsMatchingBit(self, bit) -> None: ...
    def Uniquify(self, verbose: bool = ...) -> None: ...
