from rdkit import Chem as Chem, RDLogger as RDLogger
from rdkit.Chem import ChemicalFeatures as ChemicalFeatures
from typing import Any

logger: Any
splitExpr: Any

def GetAtomFeatInfo(factory, mol): ...
def initParser(): ...
def existingFile(filename): ...
def processArgs(args, parser) -> None: ...
def main() -> None: ...
