from rdkit.Chem.rdfiltercatalog import *
from rdkit import Chem as Chem
from typing import Any

class FilterMatcher(PythonFilterMatcher):
    name: Any
    def __init__(self, name: str = ...) -> None: ...
    def HasMatch(self, mol) -> None: ...
    def GetMatches(self, mol, matchVect): ...
    def IsValid(self, mol) -> None: ...
    def GetName(self): ...
