from typing import Any

INCHI_AVAILABLE: bool

class InchiReadWriteError(Exception): ...

def MolFromInchi(inchi, sanitize: bool = ..., removeHs: bool = ..., logLevel: Any | None = ..., treatWarningAsError: bool = ...): ...
def MolToInchiAndAuxInfo(mol, options: str = ..., logLevel: Any | None = ..., treatWarningAsError: bool = ...): ...
def MolBlockToInchiAndAuxInfo(molblock, options: str = ..., logLevel: Any | None = ..., treatWarningAsError: bool = ...): ...
def MolToInchi(mol, options: str = ..., logLevel: Any | None = ..., treatWarningAsError: bool = ...): ...
def MolBlockToInchi(molblock, options: str = ..., logLevel: Any | None = ..., treatWarningAsError: bool = ...): ...
def InchiToInchiKey(inchi): ...
def MolToInchiKey(mol, options: str = ...): ...
