from rdkit.sping.pid import *
from . import psmetrics as psmetrics
from typing import Any

class PostScriptLevelException(ValueError): ...

linesep: str
PiddleLegalFonts: Any
Roman: str
Bold: str
Italic: str
PSFontMapStdEnc: Any
PSFontMapLatin1Enc: Any

def latin1FontEncoding(fontname): ...
def dashLineDefinition(): ...

class PsDSC:
    def __init__(self) -> None: ...
    def documentHeader(self): ...
    def boundingBoxStr(self, x0, y0, x1, y1): ...
    inPageFlag: int
    def BeginPageStr(self, pageSetupStr, pageName: Any | None = ...): ...
    def EndPageStr(self): ...

class EpsDSC(PsDSC):
    def __init__(self) -> None: ...
    def documentHeader(self): ...

class PSCanvas(Canvas):
    filename: Any
    drawImage: Any
    code: Any
    dsc: Any
    defaultFont: Any
    fontMapEncoding: Any
    pageNum: int
    def __init__(self, size=..., name: str = ..., PostScriptLevel: int = ..., fontMapEncoding=...) -> None: ...
    def psBeginDocument(self) -> None: ...
    def psEndDocument(self) -> None: ...
    def psBeginPage(self, pageName: Any | None = ...) -> None: ...
    def psEndPage(self) -> None: ...
    def nextPage(self) -> None: ...
    def clear(self) -> None: ...
    def resetToDefaults(self) -> None: ...
    def flush(self) -> None: ...
    def save(self, file: Any | None = ..., format: Any | None = ...) -> None: ...
    def stringWidth(self, s, font: Any | None = ...): ...
    def fontAscent(self, font: Any | None = ...): ...
    def fontDescent(self, font: Any | None = ...): ...
    def drawLine(self, x1, y1, x2, y2, color: Any | None = ..., width: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawLines(self, lineList, color: Any | None = ..., width: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawString(self, s, x, y, font: Any | None = ..., color: Any | None = ..., angle: int = ..., **kwargs) -> None: ...
    def drawCurve(self, x1, y1, x2, y2, x3, y3, x4, y4, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., closed: int = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawRoundRect(self, x1, y1, x2, y2, rx: int = ..., ry: int = ..., edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawEllipse(self, x1, y1, x2, y2, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawArc(self, x1, y1, x2, y2, startAng: int = ..., extent: int = ..., edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawPolygon(self, pointlist, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., closed: int = ..., dash: Any | None = ..., **kwargs) -> None: ...
    def drawFigure(self, partList, edgeColor: Any | None = ..., edgeWidth: Any | None = ..., fillColor: Any | None = ..., closed: int = ..., dash: Any | None = ..., **kwargs) -> None: ...
