from rdkit.ML.Data import SplitData as SplitData
from rdkit.ML.DecTree import ID3 as ID3, randomtest as randomtest
from typing import Any

def ChooseOptimalRoot(examples, trainExamples, testExamples, attrs, nPossibleVals, treeBuilder, nQuantBounds=..., **kwargs): ...
def CrossValidate(tree, testExamples, appendExamples: int = ...): ...
def CrossValidationDriver(examples, attrs, nPossibleVals, holdOutFrac: float = ..., silent: int = ..., calcTotalError: int = ..., treeBuilder=..., lessGreedy: int = ..., startAt: Any | None = ..., nQuantBounds=..., maxDepth: int = ..., **kwargs): ...
def TestRun() -> None: ...
