from rdkit.ML.DecTree import Tree as Tree
from typing import Any

class DecTreeNode(Tree.TreeNode):
    examples: Any
    badExamples: Any
    trainingExamples: Any
    testExamples: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def ClassifyExample(self, example, appendExamples: int = ...): ...
    def AddChild(self, name, label: Any | None = ..., data: Any | None = ..., isTerminal: int = ...): ...
    def GetExamples(self): ...
    def SetExamples(self, examples) -> None: ...
    def GetBadExamples(self): ...
    def SetBadExamples(self, examples) -> None: ...
    def GetTrainingExamples(self): ...
    def SetTrainingExamples(self, examples) -> None: ...
    def GetTestExamples(self): ...
    def SetTestExamples(self, examples) -> None: ...
    def ClearExamples(self) -> None: ...
