from rdkit.ML.DecTree import DecTree as DecTree
from rdkit.ML.InfoTheory import entropy as entropy
from typing import Any

def CalcTotalEntropy(examples, nPossibleVals): ...
def GenVarTable(examples, nPossibleVals, vars): ...
def ID3(examples, target, attrs, nPossibleVals, depth: int = ..., maxDepth: int = ..., **kwargs): ...
def ID3Boot(examples, attrs, nPossibleVals, initialVar: Any | None = ..., depth: int = ..., maxDepth: int = ..., **kwargs): ...
