from rdkit.ML.DecTree import DecTree as DecTree, Tree as Tree
from typing import Any

class QuantTreeNode(DecTree.DecTreeNode):
    qBounds: Any
    nBounds: int
    def __init__(self, *args, **kwargs) -> None: ...
    def ClassifyExample(self, example, appendExamples: int = ...): ...
    def SetQuantBounds(self, qBounds) -> None: ...
    def GetQuantBounds(self): ...
    def __cmp__(self, other): ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...
