from typing import Tuple
from enum import Enum
from openmm.unit import Quantity

class NonbondedForce(object):
    class NonbondedMethod(Enum):
        NoCutoff = 0
        CutoffNonPeriodic = 1
        CutoffPeriodic = 2
        Ewald = 3
        PME = 4
        LJPME = 5
    @property
    def NoCutoff(self) -> int: ...
    @property
    def CutoffNonPeriodic(self) -> int: ...
    @property
    def CutoffPeriodic(self) -> int: ...
    @property
    def Ewald(self) -> int: ...
    @property
    def PME(self) -> int: ...
    @property
    def LJPME(self) -> int: ...
    def getNumExceptions(self) -> int: ...
    def getExceptionParameters(
        self, index: int
    ) -> Tuple[int, int, Quantity, Quantity, Quantity,]: ...
    def getParticleParameters(
        self, index: int
    ) -> Tuple[Quantity, Quantity, Quantity,]: ...

class HarmonicBondForce(object): ...
class HarmonicAngleForce(object): ...
class PeriodicTorsionForce(object): ...
