from rdkit import RDConfig as RDConfig
from rdkit.Dbase import DbModule as DbModule
from rdkit.Dbase.DbConnection import DbConnect as DbConnect
from typing import Any

def SetDefaults(runDetails): ...

class CompositeRun:
    fields: Any
    def Store(self, db: str = ..., table: str = ..., user: str = ..., password: str = ...) -> None: ...
    def GetDataSet(self, **kwargs): ...
    def GetDataSetInfo(self, **kwargs): ...
