from rdkit.Dbase.DbConnection import DbConnect as DbConnect
from rdkit.ML import BuildComposite as BuildComposite, CompositeRun as CompositeRun, ScreenComposite as ScreenComposite
from rdkit.ML.Composite import AdjustComposite as AdjustComposite
from rdkit.ML.Data import DataUtils as DataUtils, SplitData as SplitData
from typing import Any

def message(msg) -> None: ...
def GrowIt(details, composite, progressCallback: Any | None = ..., saveIt: int = ..., setDescNames: int = ..., data: Any | None = ...): ...
def GetComposites(details): ...
def BalanceComposite(details, composite, data1: Any | None = ..., data2: Any | None = ...): ...
def ShowVersion(includeArgs: int = ...) -> None: ...
def Usage() -> None: ...
def SetDefaults(runDetails: Any | None = ...): ...
def ParseArgs(runDetails) -> None: ...
