from rdkit.ML.Composite import Composite as Composite
from typing import Any

class BayesComposite(Composite.Composite):
    resultProbs: Any
    condProbs: Any
    def Train(self, data, verbose: int = ...) -> None: ...
    modelVotes: Any
    def ClassifyExample(self, example, threshold: int = ..., verbose: int = ..., appendExample: int = ...): ...
    def __init__(self) -> None: ...

def CompositeToBayesComposite(obj) -> None: ...
def BayesCompositeToComposite(obj) -> None: ...
