from typing import Any

class DescriptorCalculationError(Exception): ...
class ClassificationError(Exception): ...

class ModelPackage:
    def __init__(self, descCalc: Any | None = ..., model: Any | None = ..., dataSet: Any | None = ..., notes: str = ...) -> None: ...
    def SetCalculator(self, calc) -> None: ...
    def GetCalculator(self): ...
    def SetModel(self, model) -> None: ...
    def GetModel(self): ...
    def SetDataset(self, data) -> None: ...
    def GetDataset(self): ...
    def SetNotes(self, notes) -> None: ...
    def GetNotes(self): ...
    def SetSupplementalData(self, suppD) -> None: ...
    def GetSupplementalData(self): ...
    def AddSupplementalData(self, data) -> None: ...
    def Classify(self, obj, label: str = ..., threshold: int = ...): ...
    def Init(self) -> None: ...
