from rdkit import Chem as Chem, Geometry as Geometry
from rdkit.Chem import rdDepictor as rdDepictor
from typing import Any

def AlignDepict(mol, core, corePattern: Any | None = ..., acceptFailure: bool = ...) -> None: ...
def initParser(): ...
def processArgs(args) -> None: ...
def main() -> None: ...
