from rdkit import Chem as Chem
from typing import Any

def Convert(suppl, outFile, keyCol: Any | None = ..., stopAfter: int = ..., includeChirality: bool = ..., smilesFrom: str = ...) -> None: ...
def initParser(): ...
def existingFile(filename): ...
def main() -> None: ...
